### ISSUE TITLE
encoding strings or structs

### ISSUE THREAD

**Issue by artknight** [dswitzer/hashids.coldfusion#3]
Hi,
I am wondering if it were possible to add the ability to encode/decode strings or structs?

**Comment by dswitzer** [comment]
This is a port of a very specific project (http://hashids.org/) that's designed for obscuring numeric values, which are common primary key identifiers.

The purpose of this implementation is to have a compatible port with the other versions of the library. If you are looking for functionality outside of the spec, you should look at other alternatives.

You can certainly serialize a struct in ColdFusion to a string and CF has a number of encrypting algorithms available, so it's not difficult to implement what you asking to do. But there are no plans for this library to support it.

**Comment by artknight** [comment]
That is true, which is exactly what I have been doing. The problem is that
using any of the algs the encoded string is quite long. Do you know of any
possible  algorithms with the shorter encoded length?

Thanks

-- Arthur

**Comment by dswitzer** [comment]
I suspect you will find any kind of encoding/encryption is generally going to enlarge the data--unless the data is large enough that compression the data is beneficial.

What problem are you trying to solve by encryption/encoding large strings?

**Comment by artknight** [comment]
The actual struct is usually not that long e.q. { id:5, name:”Art” }… but
when an algorithm is applied to a serialized string to encode it for
passing in the URL, it just blows up.

-- Arthur

**Comment by dswitzer** [comment]
Why are you trying to encrypt/encode that? What business problem are you 
trying to solve?

On 3/24/2016 1:16 PM, Arthur wrote:

> The actual struct is usually not that long e.q. { id:5, name:”Art” }… but
> when an algorithm is applied to a serialized string to encode it for
> passing in the URL, it just blows up.
> 
> -- Arthur
> 
> On Thu, Mar 24, 2016 at 1:03 PM, Dan G. Switzer, II <
> notifications@github.com> wrote:
> 
> > I suspect you will find any kind of encoding/encryption is generally 
> > going
> > to enlarge the data--unless the data is large enough that 
> > compression the
> > data is beneficial.
> > 
> > What problem are you trying to solve by encryption/encoding large 
> > strings?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/dswitzer/hashids.coldfusion/issues/3#issuecomment-200928258
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/dswitzer/hashids.coldfusion/issues/3#issuecomment-200933453

## 

Dan G. Switzer, II
dswitzer@pengoworks.com
http://blog.pengoworks.com/

**Comment by artknight** [comment]
I just do not want to show to the user what i am passing in the url. This
mechanism is used on pages where unique downloads are being requested, so
the struct consists of _user_id_ and _file_id_

The information is pretty much public, so there are no security concerns.

Arthur

-- Arthur

**Comment by dswitzer** [comment]
Shouldn't you know the "user_id" from the active users session? If you 
really need to obfuscate both values, then I'd serialize the values to a 
very simple string format, then encode/encrypt that. So, instead of:

{id: 5, name:"Art"}

Do:

5|Art

Then just transform that string. The shorter the string, the smaller the 
encoding/encrypting string will be.

Just keep in mind that long URLs can cause problems with certain 
browsers, proxies, etc.

If this were something I was doing, I'd try grabbing the user from their 
session information and mapping the file to value I can easily obfuscate.

On 3/24/2016 2:00 PM, Arthur wrote:

> I just do not want to show to the user what i am passing in the url. This
> mechanism is used on pages where unique downloads are being requested, so
> the struct consists of _user_id_ and _file_id_
> 
> The information is pretty much public, so there are no security concerns.
> 
> Arthur
> 
> -- Arthur
> 
> On Thu, Mar 24, 2016 at 1:56 PM, Dan G. Switzer, II <
> notifications@github.com> wrote:
> 
> > Why are you trying to encrypt/encode that? What business problem are you
> > trying to solve?
> > 
> > On 3/24/2016 1:16 PM, Arthur wrote:
> > 
> > > The actual struct is usually not that long e.q. { id:5, name:”Art” 
> > > }… but
> > > when an algorithm is applied to a serialized string to encode it for
> > > passing in the URL, it just blows up.
> > > 
> > > -- Arthur
> > > 
> > > On Thu, Mar 24, 2016 at 1:03 PM, Dan G. Switzer, II <
> > > notifications@github.com> wrote:
> > > 
> > > > I suspect you will find any kind of encoding/encryption is generally
> > > > going
> > > > to enlarge the data--unless the data is large enough that
> > > > compression the
> > > > data is beneficial.
> > > > 
> > > > What problem are you trying to solve by encryption/encoding large
> > > > strings?
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > <
> > 
> > https://github.com/dswitzer/hashids.coldfusion/issues/3#issuecomment-200928258
> > 
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/dswitzer/hashids.coldfusion/issues/3#issuecomment-200933453
> > 
> > 
> > ## 
> > 
> > Dan G. Switzer, II
> > dswitzer@pengoworks.com
> > http://blog.pengoworks.com/
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/dswitzer/hashids.coldfusion/issues/3#issuecomment-200949624
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/dswitzer/hashids.coldfusion/issues/3#issuecomment-200951063

## 

Dan G. Switzer, II
dswitzer@pengoworks.com
http://blog.pengoworks.com/
